default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cvmapper_development

test:
  <<: *default
  database: cvmapper_test

production:
  <<: *default
  database: cvmapper
  username: cvmapper
  password: <%= ENV['CVMAPPER_DB_PASSWORD'] %>
